/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author fanfaz
 */
public class menuutamaadmin extends javax.swing.JFrame {

    /**
     * Creates new form menuutamaadmin
     */
    public menuutamaadmin() {
        initComponents();
    }

    public JButton getBtnDataKelGeladi() {
        return BtnDataKelGeladi;
    }

    public JButton getBtnDataMahasiswa() {
        return BtnDataMahasiswa;
    }

    public JButton getBtnDataPem() {
        return BtnDataPem;
    }

    public JButton getBtnLogout() {
        return BtnLogout;
    }

    public void setBtnDataKelGeladi(JButton BtnDataKelGeladi) {
        this.BtnDataKelGeladi = BtnDataKelGeladi;
    }

    public void setBtnDataMahasiswa(JButton BtnDataMahasiswa) {
        this.BtnDataMahasiswa = BtnDataMahasiswa;
    }

    public void setBtnDataPem(JButton BtnDataPem) {
        this.BtnDataPem = BtnDataPem;
    }

    public void setBtnLogout(JButton BtnLogout) {
        this.BtnLogout = BtnLogout;
    }
    
    public void addListener(ActionListener e){
        BtnDataKelGeladi.addActionListener(e);
        BtnDataMahasiswa.addActionListener(e);
        BtnDataPem.addActionListener(e);
        BtnLogout.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnDataKelGeladi = new javax.swing.JButton();
        BtnDataPem = new javax.swing.JButton();
        BtnDataMahasiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MENU UTAMA ADMIN");

        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sign out.png"))); // NOI18N
        BtnLogout.setText("jButton4");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnDataKelGeladi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data Kelompok Geladi.png"))); // NOI18N
        BtnDataKelGeladi.setText("jButton1");
        BtnDataKelGeladi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDataKelGeladiActionPerformed(evt);
            }
        });

        BtnDataPem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data Pembimbing.png"))); // NOI18N
        BtnDataPem.setText("jButton2");

        BtnDataMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data Mahasiswa.png"))); // NOI18N
        BtnDataMahasiswa.setText("jButton3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnDataKelGeladi, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDataPem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDataMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDataKelGeladi)
                    .addComponent(BtnDataPem)
                    .addComponent(BtnDataMahasiswa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(184, 184, 184)
                            .addComponent(jLabel1)
                            .addGap(159, 159, 159))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BtnLogout)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDataKelGeladiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDataKelGeladiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDataKelGeladiActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDataKelGeladi;
    private javax.swing.JButton BtnDataMahasiswa;
    private javax.swing.JButton BtnDataPem;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
